name: Backend CI

on:
  push:
    branches:
      - main  # Trigger on push to 'main' branch
  pull_request:
    branches:
      - main  # Trigger on pull requests targeting 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use Ubuntu environment

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2  # Checkout your code

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '22'  # Use Node.js version 22

      - name: Install dependencies
        run: |
          cd aegis-backend
          npm install

      - name: Build backend
        run: |
          cd aegis-backend
          npm run build  # Build Strapi project
